###
### Global config
###
image: docker:git
services:
- docker:dind
stages:
- build
- cascade

###
### Build @ gitlab.cylian.org
###
build:cylian.org:
  stage: build
  tags:
  - docker

  ### Prepare environment
  before_script:
  - export readonly PROJECT_VERSION=$(git describe --abbrev=0 --tags)
  - command -v envsubst || apk add gettext
  - echo "${CI_REGISTRY_PASSWORD}" | docker login --username "${CI_REGISTRY_USER}" --password-stdin "${CI_REGISTRY}"

  ### Build image
  script:
  - >
    for dockerfile in Dockerfile.* ; do
      export PROJECT_FLAVOUR=${dockerfile##*.}
      envsubst < ${dockerfile} > Dockerfile
      echo "Building flavour=${PROJECT_FLAVOUR} version=${PROJECT_VERSION}"
      docker build --pull \
        --tag "${CI_REGISTRY_IMAGE}:${PROJECT_VERSION}-${PROJECT_FLAVOUR}" \
        --tag "${CI_REGISTRY_IMAGE}:${PROJECT_FLAVOUR}" \
        .
    done
  - docker push --all-tags "${CI_REGISTRY_IMAGE}"

  ### Cleanup environment
  after_script:
  - docker logout "${CI_REGISTRY}"

###
### Build @ hub.docker.com
###
build:docker.com:
  stage: build
  tags:
  - docker
  only:
  - main
  
  ### Prepare environment
  before_script:
  - export readonly PROJECT_VERSION=$(git describe --abbrev=0 --tags)
  - export readonly PROJECT_IMAGE="cylian/console"
  - command -v envsubst || apk add gettext
  - echo "${CI_REGISTRY_PASSWORD}" | docker login --username "${CI_REGISTRY_USER}" --password-stdin "${CI_REGISTRY}"
  - echo "${DOCKER_HUB_PASSWORD}"  | docker login --username "${DOCKER_HUB_USER}"  --password-stdin

  ### Build image
  script:
  - >
    for dockerfile in Dockerfile.* ; do
      export PROJECT_FLAVOUR=${dockerfile##*.}
      envsubst < ${dockerfile} > Dockerfile
      echo "Building flavour=${PROJECT_FLAVOUR} version=${PROJECT_VERSION}"
      docker build --pull \
        --tag "${PROJECT_IMAGE}:${PROJECT_VERSION}-${PROJECT_FLAVOUR}" \
        --tag "${PROJECT_IMAGE}:${PROJECT_FLAVOUR}" \
        .
    done
  - docker push --all-tags "${PROJECT_IMAGE}"

  ### Cleanup environment
  after_script:
  - docker logout
  - docker logout "${CI_REGISTRY}"

###
### Cascase
###
cascade:cylian.org:
  stage: cascade
  tags:
  - alpine
  needs:
  - build:cylian.org
  only:
  - main

  ### Prepare environment
  before_script:
  - command -v curl || apk add --no-cache curl

  ### Cascade builds image
  script:

  # [118] gitlab-builder/console
  - curl -s -X POST -F token=${CI_JOB_TOKEN} -F ref=${CI_COMMIT_REF_NAME} https://gitlab.cylian.org/api/v4/projects/118/trigger/pipeline
