###
### Console
###
FROM alpine:latest as console

COPY config/ /usr/local/console/config
COPY core/ /usr/local/console/core
COPY console.py /usr/local/console/

RUN chmod 755 /usr/local/console/console.py
RUN ln -s /usr/local/console/console.py /usr/local/bin/console

###
### Image
###
FROM alpine:latest

### Maintener
LABEL maintainer="Cylian Lab <contact+docker@cylian.org>"

### Install tools
RUN apk add --no-cache \
    python3 \
    py3-yaml

### Install console
COPY --from=console /usr/local/console /usr/local
COPY --from=console /usr/local/bin/console /usr/local/bin

### Entrypoint
ENTRYPOINT [ "/usr/local/console/console.py" ]
CMD [ "help" ]